Autodesk/hubble

- docs/_layouts/default.html
- docs/assets/css/stylesheet.css
Unfortunately, I referenced the logo with an absolute URL, which doesn’t work on the hosted page at [autodesk.github.io/hubble](). Also, I accidentally included the logo twice. This pull requests corrects these issues to make the logo render properly.
> Fix incorrect logo URL

- docs/demo-data/api-requests-detailed.tsv
- docs/demo-data/api-requests.tsv
- docs/demo-data/forks-to-organizations-detailed.tsv
- docs/demo-data/forks-to-organizations.tsv
- docs/demo-data/git-download-detailed.tsv
- docs/demo-data/git-download.tsv
- docs/demo-data/git-requests-detailed.tsv
- docs/demo-data/git-requests.tsv
- docs/demo-data/git-versions.tsv
- docs/demo-data/pull-request-usage.tsv
- docs/demo-data/tokenless-authentication-detailed.tsv
- docs/demo-data/tokenless-authentication.tsv
- docs/housekeeping-git-traffic.html
- updater/reports/ReportAPIRequests.py
- updater/reports/ReportForksToOrgs.py
- updater/reports/ReportGitDownload.py
- updater/reports/ReportGitRequests.py
- updater/reports/ReportPRUsage.py
- updater/reports/ReportTokenlessAuth.py
- updater/scripts/api-requests.sh
- updater/scripts/git-download.sh
- updater/scripts/git-requests.sh
- updater/scripts/git-versions.sh
- updater/scripts/tokenless-auth.sh
The data labels are currently formatted inconsistently. This pull request turns all labels into lowercase (except acronyms etc.) and updates the demo data accordingly.
> Make data labels consistent

- README.md
@rashamalek made me aware that the part about the `dataURL` is slightly confusing.
For this reason, I suggest adding an example URL and making it more clear that the `dataURL` is actually hosted by GitHub Pages and not just the repository URL.
@rashamalek: Do you think this is precise enough in order to set everything up correctly, or do you have another suggestion?
> Clarify that dataURL is a GitHub Pages URL

- updater/scripts/git-download.sh
In GHE 2.11 the audit log location was changed. Check the GHE version
to support pre 2.11 log location and the new log location.
> add support for GHE 2.11 audit log location

- README.md
The other section headers in the readme are all in title case. For this reason, the “license” section header should also be set in title case.
> Set “license” header in readme in title case

- docs/_layouts/default.html
Ref: #16 
Uses site.url and removes the "https://" part.
> Remove inline JavaScript from header and replace it with Jekyll directive

- docs/_layouts/default.html
If GHE subdomain isolation is enabled, then all pages URLs are 
prefixed with `pages.`. Remove this prefix in the page header. 
In addition, only remove the first occurrences of `http://` (although we 
shouldn't see that string multiple times).
@parkr is there an easier way to achieve the same? 😄 
/cc @GitHugop
> Cleanup GHE URL in header

- updater/scripts/git-download.sh
An exit code of 0 indicates success and an exit code of 1 indicates
failure in bash. Flip the version comparision operator in Perl to
implement "ghe_greater_equal" properly.
In addition, define the required version with three segments as this
seems to be required by the Perl version parser.
Thanks to @toddocon for pointing out the issue to me!
---
Unfortunately, this does not yet fix the download graph for GHE 2.11.
It looks like the log rotation frequency for /var/log/github-audit.log
changed from daily to weekly. I've asked GH support if this change
was intentional. If yes, then we need to adjust our audit log data 
gathering as the current code expects the daily rotation.
> git-download: fix GHE version detection

- docs/assets/js/charts.js
The colors of the first few organizations were very close to each other, making it hard to differentiate them. This commit shuffles the colors so that consecutive colors are contrasting.
WIth this change, the first colors to be selected are (from left to right):
> Shuffle colors for better differntiation in collaboration chart

- docs/assets/js/charts.js
If the collaboration chart of a single organization is visualized, then
ensure that the choosen org is always drawn first. This way the choosen
org is always drawn with the same color.
In addition, rotate the color wheel to start with the color "blue"
because I think it looks good.
> Collaboration chart: draw chosen org first, make first org blue

- docs/_data/navigation.yml
- docs/assets/js/charts.js
- docs/demo-data/org-owners.tsv
- docs/org-owners.html
- updater/reports/Report.py
- updater/reports/ReportContributorsByOrg.py
- updater/reports/ReportContributorsByRepo.py
- updater/reports/ReportForksToOrgs.py
- updater/reports/ReportOrgCollaboration.py
- updater/reports/ReportOrgOwners.py
- updater/reports/ReportPRByOrg.py
- updater/reports/ReportPRByRepo.py
- updater/reports/ReportPRHistory.py
- updater/reports/ReportRepoActivity.py
- updater/reports/ReportRepositoryHistory.py
- updater/reports/ReportUsers.py
- updater/update-stats.py
Based on @mlbright and @pluehne 's work in #36 I finished the org owners feature. If you have time, please give it a look.
> List: organization owners (v2)

- docs/assets/css/stylesheet.css
Previously, hyphenation was enabled for all HTML elements in the dashboard. However, this is not very helpful with organization names, as it’s important to know whether the organization name contains an extra hyphen or not.
For this reason, this commit enables hyphenation for info boxes only, for which hyphenation was originally intended, as the text columns within info boxes are rather small.
Aside from that, I smuggled in a minor cleanup commit (6c000aa2f6f2583ae245bdd4598601556d793922).
> Hyphenate within info boxes only

- docs/assets/js/charts.js
This adds anchors to items in the first columns of tables. This is useful, for instance, to send links directly referencing a row in the tables (where the first column usually some sort of index).
To disambiguate the anchor IDs in the case that there are multiple tables on the same page, anchors are automatically prefixed with the table’s own ID.
Additionally, 06d39d1117b4e1f4f147509b24eca4d4c25eb5ed fixes the HTML output. Previously, tabes introduced tags of type `<undefined>` whenever the table cell content wasn’t a link.
> Add anchors to items in first table columns

- updater/scripts/git-download.sh
The "github-audit.log" log file introduced in GHE 2.11.0 is only rolled
once a week. This was reported as bug and is likely fixed in an upcoming
version. In the meantime we grep for all log entries that have been
written yesterday.
> fix Git download chart for GHE 2.11.0

- updater/update-stats.py
The configuration option `excludedEntities` is now a list and not a pure string anymore. In order not to break existing systems, automatically make a list out of the setting if it isn’t already.
I deliberately implemented this in [`update-stats.py`](updater/update-stats.py) and not in the [`addExcludedEntities`](https://github.com/Autodesk/hubble/blob/c782eee822f80a70b61b8fb9e66ec40653d0e644/updater/reports/Report.py#L205-L210) function (where it’s used) in order to make the change consistent—should this setting be read at another place, for instance.
> Backward compatibility for excludedEntities config

- README.md
- updater/scripts/git-download.sh
This fixes an issue where the log files read by Hubble were empty, which is why the Git download report got 0 traffic as a result.
This lets the Git download script check not only for log entries in the previous Git audit log but also the current one. Because of the unwanted log rotation change introduced in GitHub Enterprise 2.11, we can’t assume that the log files searched for with .1* contain yesterday’s information (it might still reside in the current, not-yet-rotated log).
I tested this on a GitHub Enterprise 2.11.2 machine, and I’m confident that this doesn’t break 2.10 support.
> Fix Git download script

- updater/scripts/tokenless-auth.sh
In this script, user names were read from LDAP, where underscores and periods are allowed characters. However, these characters aren’t allowed in GitHub user names, which is why they are replaced with dashes.
Because of this, user names containing underscores and periods weren’t linked correctly in the tokenless authentications list. This pull request fixes this by performing the substitution directly within the affected script.
> Fix user names in tokenless authentications script

- updater/scripts/api-requests.sh
The IP address is parsed with a greedy search for ":" in the haproxy
logs. Apparently GitHub Enterprise adds other colons in some situations
that confuse this search. E.g. "Operation: California" in this example:
```
Nov 23 15:12:08 octodemo-com-primary haproxy[27650]: 127.0.0.1:60001 [23/Nov/2017:15:12:08.418] https_protocol~ web_unicorns/localhost 0/0/0/79/79 200 45447 - - ---- 13/6/1/1/0 0/0 {octodemo.com||Operation: California Auto-Deploy} "GET /api/v3/repos/lukeartorg/reading-time-demo-lukeart/deployments HTTP/1.1"
```
Narrow the regex pattern to detect the IP address properly.
Reported-by: Johannes Nicolai <@jonico>
> api-requests: fix haproxy IP address parsing

- updater/scripts/git-download.sh
In 50743c8 we implemented a workaround for the GitHub audit log rotation
bug. The solution was to find the log lines from yesterday in the files
that contain all logs from the last week. To achieve this we grep for
yesterday's date.
The day component of the date was padded with zeros (e.g. "Dec 04").
However, in the GitHub audit log the date is padded with spaces (e.g.
"Dec  4"). Consequently, the grep did not match for single digit days.
Fix that by padding the day with spaces.
> git-download: fix audit log grepping workaround for GHE 2.11+

- updater/scripts/git-download.sh
Using "log{,.1*}" would print the ".log" file first and afterwards the
".log.1*". This would break the chronocial order (see example below).
Fix this problem by defining the order explitcly.
This problem did not affect the current implementation. However, I think
printing the log items in chronological order is a good idea to avoid
surprises in the future.
Example:
$ zcat -f /var/log/github-audit.log{,.1*} | cut -c -6 | uniq -c
146 Dec  3
238 Dec  4
138 Dec  5
190 Nov 27
264 Nov 28
250 Nov 29
249 Nov 30
233 Dec  1
189 Dec  2
52 Dec  3
$ zcat -f /var/log/github-audit.{log.1*,log} | cut -c -6 | uniq -c
190 Nov 27
264 Nov 28
250 Nov 29
249 Nov 30
233 Dec  1
189 Dec  2
199 Dec  3
238 Dec  4
138 Dec  5
> git-download: print audit logs in chronological order

- docs/assets/js/charts.js
- docs/spec/charts.js
- docs/spec/karma.conf.js
Sorry about the bug with the spinner, my bad!
I've fixed that in this pull request by ensuring we remove the container housing the spinner from the DOM after calling `stop` on it. I also added a test for this to our new test framework to ensure we don't regress on this in the future :)
> Fixes #62: spinner container gets in the way of mouseover events with charts

- updater/README.md
- updater/packaging/debian/templates/Makefile
- updater/systemd/hubble-enterprise.service
- updater/systemd/hubble-enterprise.timer
This makes the `systemd` system service a user service. There are two reasons that motivated this change.
1. User services require an active session of the specified user. This has the drawback that the updater would not be triggered after reboots if no SSH connection to the GitHub Enterprise appliance was made (see also #71, which should be fixed by this pull request).
1. User services cannot depend on system services. Because of that, the updater service could not reliably wait for the rest of GitHub Enterprise to start.
> Switch updater to systemd system service

- docs/package-lock.json
- docs/package.json
- docs/spec/karma.conf.js
Also removes unused JavaScript dependencies.
Now, upon running `npm test`, you can see how much of the JavaScript code is being "covered" by the unit tests:
```
➔ npm test
> hubble-web-application@0.0.1 test /Users/maj/src/hubble/docs
> karma start spec/karma.conf.js
20 12 2017 15:07:32.269:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
20 12 2017 15:07:32.272:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
20 12 2017 15:07:32.278:INFO [launcher]: Starting browser ChromeHeadless
20 12 2017 15:07:32.702:INFO [HeadlessChrome 0.0.0 (Mac OS X 10.13.2)]: Connected on socket Q--jAqfE1PHvWhX_AAAA with id 99752543
HeadlessChrome 0.0.0 (Mac OS X 10.13.2): Executed 7 of 7 SUCCESS (0.035 secs / 0.019 secs)
=============================== Coverage …
```
> Show JavaScript unit test code coverage report as part of output of `npm test`

- updater/packaging/debian/Makefile
`dh_make` recently changed from Python 2 to Python 3. For this reason, the call to `dh_make` with Python 2 won’t work on systems with new `dh_make` versions. Instead of locking the Python version to Python 2, call Python without the fixed version number. This should be safe, because we can expect Linux distributions to ship a version of `dh_make` that works with the system’s default Python version.
> Fix dh_make call for Debian packaging

- updater/scripts/git-download.sh
Some Python version apparently cannot handle Unicode characters which
causes the following error:
```
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 881: ordinal not in range(128)
```
Fix this by using ASCII only characters.
Thanks to @rajivmucheli for patiently debugging the issue with me 😄
> use ASCII only characters in scripts

- docs/assets/css/stylesheet.css
- docs/assets/js/charts.js
- docs/housekeeping-api-requests.html
- docs/housekeeping-forks.html
- docs/housekeeping-git-requests.html
- docs/housekeeping-git-traffic.html
- docs/index.html
- docs/org-owners.html
- docs/orgs-total.html
- docs/pr-total.html
- docs/pr-usage.html
- docs/recommendations.html
- docs/repos-activity.html
- docs/repos-total.html
- docs/teams-total.html
- docs/users-activity.html
- docs/users-contributors.html
- docs/users-git-versions.html
This refactoring simplifies the HTML necessary to build charts by moving the creation of required wrappers to the JavaScript side.
This approach has multiple benefits.
1. First, the HTML part is more lightweight. Hence, future additions to the charts (such as action bars) will require much less changes to the HTML.
1. Second, we have more control over the layout on the JavaScript side without having to touch the HTML part.
1. Third, information concerning the chart content is grouped and separated from the layout part more nicely in this way.
1. Finally, with this preparation, we could render placeholders more nicely in the future, as they have a distinct style now.
The existing charts are adjusted to these changes and produce pixel-wise identical visualizations. Additionally, this …
> Refactor DOM creation

- docs/assets/css/stylesheet.css
- docs/assets/js/charts.js
This adds an action bar to every chart with a button to download the raw data files in TSV format if existent. The action bar is designed to hold more actions in the future, most notably, a switch for the level of detail in the charts.
Along with the action bar, this commit introduces CSS for buttons.
Note that the action bar is to be considered as a “version 1” design to bring the functionality first, and the layout will probably change in a future release.
For reference, here is a screenshot with the new action bar highlighted:
> Add action bar with link to raw data to all charts

- docs/assets/js/charts.js
The “raw data” buttons are supposed to be shown only when a data URL is set, just as a defensive measure. By accident, this was only applied to `<canvas>` and `<svg>` elements but not `<table>`s.
This commit makes the behavior consistent by applying the check to tables as well.
> Fix behavior with “raw data” buttons for tables

- .codecov.yml
- .travis.yml
- docs/.eslintignore
- docs/.gitignore
- docs/package-lock.json
- docs/package.json
- docs/spec/karma.conf.js
I use the codecov.io service on a lot of my JavaScript projects, as it automatically comments how test code coverage changes with each incoming PR to a project. I find that feature useful. If the owners of Hubble agree, feel free to pull this PR, but please read the sections below for some details on how it all works and what permission changes are needed.
1. Every time Travis runs a CI job, it'll execute `npm run codecov` after the tests complete. This will go through and parse the JS code coverage report files that our karma test runner creates to understand what the JS code coverage level is in the PR.
2. In order to report the code coverage difference in PRs, we need to ensure that Travis-CI is building commits on the master branch, so that we have a 'base' coverage level we can …
> Closes #83: report JavaScript code coverage in PRs

- docs/assets/js/charts.js
The function “drawChord” was accidentally misspelled. I believe that it wasn’t *coordinates* that were meant but [*chords*](https://en.wikipedia.org/wiki/Chord_(geometry)), a term from geometry signifying line segments whose endpoints both reside on a circle.
> Fix typo in chord chart code

- docs/README.md
- docs/assets/css/stylesheet.css
- docs/assets/js/charts.js
- docs/index.html
This introduces a new configuration option “showRawDataLink,” through which the “raw data” button can be explicitly hidden (requested in #87).
This is used for hiding the “raw data” download button in the collaboration chart, where the raw data isn’t useful to view or edit in a spreadsheet application.
Also, the margins of chart titles were incorrect in the case that the corresponding action bar was hidden. This change applies the same style to all titles, regardless of whether an action bar is shown or not.
See how the “raw data” button is missing in the screenshot below 😄:
> Make the “raw data” button optional

- docs/_layouts/default.html
By using the GitHub Pages build hash as a “version” parameter on the asset URLs, we can force browser cache flushes of our JavaScript and CSS resources upon every commit.
While it wouldn’t be strictly necessary to change the version tag of a file on every commit (but only when it changes), this avoids having to manually change the version parameter after each change.
Note that I couldn’t test this yet, as I would have to replicate GitHub Pages somehow (maybe I could do this through a fork).
On another note, in the case that you deploy this locally, the variable `site.github.build_revision` will be rendered as an empty string. Not that that’s a problem from my point of view, but if you think this is something we should address, go ahead and tell me.
> Use GitHub build hash as parameter on assets

- docs/README.md
- docs/assets/js/charts.js
- docs/pr-total.html
- docs/pr-usage.html
- docs/spec/.eslintrc.json
- docs/spec/charts.js
This implements a generalized method for aggregating time-series data. Data can be aggregated over week or month intervals with a variety of aggregation methods to choose from.
This will be useful for providing chart views at different levels (such as two-year periods vs. just showing the last month). Additionally, the generalized form of aggregation can be used to smooth out graphs where the sampling frequency changed with an update to Hubble Enterprise.
The aggregation is done by splitting the time data into subsequent, gapless periods of time (weeks starting with Mondays or months), for each of which the aggregated values are then computed and returned.
Aggregation methods define how to aggregate the values within individual time periods. The following aggregation methods are …
> Provide generalized aggregation

- docs/_layouts/default.html
- docs/assets/js/charts.js
The “raw data” link was very verbose and, perhaps, not as easily recognizible for a download button than the Font Awesome download icon.
Replacing the text “raw data” with an icon also saves some space that we’ll need in the action bar to add a detail view switch.
> Replace text in “raw data” download button with icon

- docs/_data/navigation.yml
- docs/demo-data/organizations-abandoned-detailed.tsv
- docs/demo-data/organizations-abandoned.tsv
- docs/housekeeping-abandoned-orgs.html
- updater/reports/ReportOrgsAbandoned.py
- updater/update-stats.py
Find the organizations that have not received a push for the longest time.
Only look at organizations that have not received a push for at least one
year.
> add list of abandoned organizations

- docs/_data/navigation.yml
- docs/demo-data/repositories-personal-nonowner-pushes-detailed.tsv
- docs/demo-data/repositories-personal-nonowner-pushes.tsv
- docs/housekeeping-repo-location.html
- updater/reports/ReportReposPersonalNonOwnerPushes.py
- updater/update-stats.py
Find personal repositories that non-owners are pushing to.
These kind of repositories should be moved into organizations.
Only look at active users (not suspended!) and only look at pushes
of the last 4 weeks.
> add list of personal repositories that non-owners are pushing to

- updater/scripts/api-requests.sh
GitHub seems to use its own API for internally. Filter these requests as
we are only interested in external API usage (because we can only control
external API usage).
> remove GitHub internal API requests from API statistics

- docs/demo-data/repositories-personal-nonowner-pushes-detailed.tsv
- updater/reports/ReportReposPersonalNonOwnerPushes.py
The more people push to a personal repo, the more this repo should
become an organizational repo. Therefore, we count the number of
pushers and sort the "offender" list by it.
> count pusher in personal repos with nonowner pushes

- docs/_layouts/default.html
- docs/assets/css/stylesheet.css
I find the bold version of Open Sans too bold, especially for usage in buttons. This replaces the bold font with a semibold version, which also looks nice in headings.
Here is an overview for comparison:
> Change to lighter bold font

- docs/README.md
- docs/assets/js/charts.js
- docs/pr-total.html
- docs/users-contributors.html
For consitency with the `aggregate` option, this renames the `sliceData` option to simply `slice`.
> Rename “sliceData” option to “slice”

- updater/helpers.py
- updater/reports/Report.py
- updater/update-stats.py
I want to add a data repository scheme check to Hubble, which will share the data repository preparation steps with `update-stats.py`. For this reason, I thought it would be best to move these steps into a new helper module (see db13f474d9678957e6ed7d7ab46feedac4b778ce) so that they can be reused later on.
At the same time, I remembered that the `Report` module contained multiple helpers that don’t really belong there. For this reason, I moved them into the helper module as well (see c83d974f2e88598b506a67065f38af36085ed221).
I tested the changes and verified that everything works just as before.
> Move helper functions to separate module

- updater/scripts/git-download.sh
GHE 2.11.0 wrongly rolled the audit log only once a week. This problem
was fixed in 2.11.6. Limit the workaround to this version range.
> git-download: limit workaround for audit log roll bug

- updater/check-schema.py
- updater/schema.py
- updater/update-stats.py
With this addition, the updater checks the schema version of the data in the data repository before attempting to run. In the case that the schema is outdated, an error is returned indicating that a migration
needs to be performed manually.
Additionally, the new script `check-schema.py` can be manually invoked to check the data schema prior to actually running the updater.
> Add forward compatibility check to updater

- docs/_data/navigation.yml
- docs/demo-data/repository-usage.tsv
- docs/repos-activity.html
- docs/repos-feature-usage.html
- docs/repos-total.html
- updater/reports/ReportPRUsage.py
- updater/reports/ReportRepoActivity.py
- updater/reports/ReportRepoUsage.py
- updater/update-stats.py
Calculate percentage of active repositories over the last four weeks
in organizations that have received pushes to at least one protected
branch and that have at least one topic assigned to them.
This way we can track if people use protected branches and topics!
---
Please review by commit. 1-3 are preparation, 4 is the beef 😄
> add repo usage report

- docs/assets/js/charts.js
This replaces clunky functors (mainly used for map/reduce calls) with the cleaner arrow functions.
Arrow functions have been supported by all modern browsers for quite some time now (yes, this excludes Internet Explorer, but we don’t support it anyway).
In addition to this, I performed some other minor refactorings that I want to have in place before opening a pull request for #115.
> Simplify functors with JavaScript’s arrow syntax

- docs/assets/js/charts.js
- docs/demo-data/repository-activity-detailed.tsv
- docs/repos-activity.html
- updater/reports/ReportRepoActivity.py
Based on @mlbright 's work in #119 I did the following:
- move the "active repos table" into the "active repos section" (I know we discussed that before and I think I asked you to move it to the "repo usage" section ... no idea why I said that ... that was stupid of me)
- display pusher count and push count
- display repository `org/repo` to make the auto linking to GHE work
- added demo data
- squashed commits
@mlbright please review!
> list of active repositories (refactored)

- docs/assets/js/charts.js
Due to a mistake (see #120), the aggregation method was invoked only on the new multiview charts but not on single-view charts. With this change, single-view charts are handled like multiview charts with only one view. This fixes the aggregation issue, makes things more consistent, and cleans up the code.
Fixes #120.
> Apply aggregation for single-view charts

- docs/housekeeping-abandoned-orgs.html
- docs/housekeeping-api-requests.html
- docs/housekeeping-forks.html
- docs/housekeeping-git-requests.html
- docs/housekeeping-git-traffic.html
- docs/housekeeping-repo-location.html
- docs/orgs-activity.html
- docs/orgs-total.html
- docs/pr-usage.html
- docs/recommendations-legacy-teams.html
- docs/recommendations-tokenless-auth.html
- docs/repos-activity.html
- docs/repos-feature-usage.html
- docs/repos-total.html
- docs/teams-total.html
- docs/users-activity.html
This makes all remaining history charts multiview-capable. For most charts, it made sense to select one value of each time period for weekly aggregation, while for a few others, computing the sum was more apt.
I know that the configuration is kind of clunky. However, I’d like to keep it like this for some time until we have an intuition of whether we should make some of these configuration values defaults or not.
> Enable multiple views on all history charts

- docs/assets/js/charts.js
Clicks on the view switcher buttons are supposed to be handled by JavaScript in order to switch the active view, bypassing the browser. However, without telling the browser that the click events have been reacted to, it will load the URL as usual. As the view switcher buttons have a `#` placeholder link, this would cause the browser to jump to to the top of the page.
This is fixed by returning `false` in the click event handling functions.
> Don’t jump to top of the page when switching views

- docs/assets/js/charts.js
When aggregating over only few data points, the weekly-aggregated views might end up empty. This led to an error, because the chart generation relied on the data not to be empty.
This adds a corresponding check, which prevents the error and shows an empty chart as expected.
Instead of showing users empty charts, views with no data should be hidden from the users. This will be addressed separately (tracked in issue #133).
Note that with the meek amounts of demo data that we currently have, many chart views in the [interactive demo](https://autodesk.github.io/hubble/) end up empty. This should be addressed as suggested in #132.
Fixes #128.
> Fix error with empty chart views

- docs/demo-data/api-requests-detailed.tsv
- docs/demo-data/api-requests.tsv
- docs/demo-data/git-download-detailed.tsv
- docs/demo-data/git-download.tsv
- docs/demo-data/git-requests-detailed.tsv
- docs/demo-data/git-requests.tsv
- docs/demo-data/tokenless-authentication-detailed.tsv
- docs/demo-data/tokenless-authentication.tsv
- docs/housekeeping-git-traffic.html
- updater/reports/ReportAPIRequests.py
- updater/reports/ReportGitDownload.py
- updater/reports/ReportGitRequests.py
- updater/reports/ReportTokenlessAuth.py
- updater/scripts/api-requests.sh
- updater/scripts/git-download.sh
- updater/scripts/git-requests.sh
- updater/scripts/tokenless-auth.sh
With the recent addition of multiple views with aggregated data, the `/day` label suffix doesn’t make sense in cases where weekly data is actually shown.
This removes the suffix from all labels to avoid confusion.
Note that Hubble will apply the header change upon the next run after applying the update. This means that between the time of applying the update and running Hubble, the web frontend will show empty charts, because the data series labels won’t match. However, I think that this is an acceptable caveat.
> Remove the “/day” suffix from data series labels

- updater/reports/ReportAPIRequests.py
- updater/reports/ReportContributorsByOrg.py
- updater/reports/ReportContributorsByRepo.py
- updater/reports/ReportForksToOrgs.py
- updater/reports/ReportGitDownload.py
- updater/reports/ReportGitRequests.py
- updater/reports/ReportGitVersions.py
- updater/reports/ReportOrgActivity.py
- updater/reports/ReportOrgCollaboration.py
- updater/reports/ReportOrgOwners.py
- updater/reports/ReportOrgsAbandoned.py
- updater/reports/ReportOrgsTotal.py
- updater/reports/ReportPRByOrg.py
- updater/reports/ReportPRByRepo.py
- updater/reports/ReportPRHistory.py
- updater/reports/ReportPRUsage.py
- updater/reports/ReportRepoActivity.py
- updater/reports/ReportRepoUsage.py
- updater/reports/ReportReposPersonalNonOwnerPushes.py
- updater/reports/ReportRepositoryHistory.py
- updater/reports/ReportTeamsLegacy.py
- updater/reports/ReportTeamsTotal.py
- updater/reports/ReportTokenlessAuth.py
- updater/reports/ReportUsers.py
I got a little bit frustrated at the fact that our reports are not very consistent structure-wise. As I don’t want to encourage contributors (and myself) to continue this trend, I thought it best to clean this all up :smiley:.
For this reason, this pull request applies multiple minor refactorings and reformattings.
I verified that there are no semantic changes whatsoever, and tested that the results obtained with this patch are the same as without it.
1. Make unused return variables anonymous.
2. Some weird-looking 1TBS indentations are reformatted.
3. Separate operators from the operands with spaces.
4. Remove unused return variables and return directly instead.
5. Put connective operators at the beginning of new lines.
6. Break long lines appropriately.
7. Capitalize SQL keywords.
8. …
> Minor refactorings and reformattings

- updater/reports/ReportAPIRequests.py
- updater/reports/ReportForksToOrgs.py
- updater/reports/ReportGitDownload.py
- updater/reports/ReportGitRequests.py
- updater/reports/ReportOrgsAbandoned.py
- updater/reports/ReportOrgsTotal.py
- updater/reports/ReportPRHistory.py
- updater/reports/ReportPRUsage.py
- updater/reports/ReportRepoActivity.py
- updater/reports/ReportRepoUsage.py
- updater/reports/ReportReposPersonalNonOwnerPushes.py
- updater/reports/ReportRepositoryHistory.py
- updater/reports/ReportTeamsLegacy.py
- updater/reports/ReportTeamsTotal.py
- updater/reports/ReportTokenlessAuth.py
- updater/reports/ReportUsers.py
With this commit, every single update will cause the data file headers to be rewritten to their defaults.
In this way, we can easily change column labels in the data files in the future without having to worry about empty charts due to the inconsistent naming scheme (which causes the dashboard not to match the data series with the columns appropriately).
I don’t consider this a change that could accidentally break data by, for instance, switching the meaning of columns in the future. The reason is that we have the data schema mechanism in place to deal with cases where we would like to make deeper changes to the data format that would require a data migration.
> Rewrite headers on every update

- docs/demo-data/users.tsv
- docs/users-activity.html
- updater/reports/ReportUsers.py
The user activity chart stems from before most sliding windows and aggregation methods were switched from 30-day intervals to 4-week intervals. The benefit of this is that weekends are evened out, which avoids accidentally misinterpreting some fluctuations.
This changes the user activity chart accordingly for consistency.
Additionally, the time range computation in the updater report receives a minor refactoring based on the more recent reports.
Note that this change will invalidate previously recorded data based on 30-day intervals. However, no action is taken, because the difference between data aggregated over 28 and 30 days is expected to be subtle.
Resolves #129.
> Switch user activity chart to 4-week intervals

- updater/scripts/tokenless-auth.sh
The format of the `gitauth.log` file changed from GitHub Enterprise 2.11 to 2.12. This makes it necessary to adjust the regular expression responsible for fetching user names and repositories.
Unfortunately, it seems that we can no longer rely on the order of the fields in gitauth.log. For this reason, multiple grep iterations are performed and the regular expression is changed to use look-aheads to allow for arbitrary field orders.
For backward compatibility with GitHub Enterprise 2.11 and earlier, a switch is implemented that executes the old query if necessary.
Addresses the second issue mentioned in #139.
> Fix tokenless authentication chart

- docs/assets/js/charts.js
- docs/housekeeping-abandoned-orgs.html
- docs/housekeeping-api-requests.html
- docs/housekeeping-forks.html
- docs/housekeeping-git-requests.html
- docs/housekeeping-git-traffic.html
- docs/housekeeping-repo-location.html
- docs/org-owners.html
- docs/recommendations-legacy-teams.html
- docs/recommendations-tokenless-auth.html
- docs/repos-activity.html
This adds an explicit chart type declaration to all tables. The benefit of this is that this enables users to implement custom table types (with a distinct chart type) in extensions without clashing with Hubble’s own `table` type.
> Make table chart type explicit

- updater/reports/ReportGitVersionsNew.py
- updater/update-stats.py
This adds an extended edition of the Git versions report. In addition to tracking the used Git versions of the last day, this tracks all used Git versions every day, making an upgrade trend chart possible.
Note that this only includes the report (which gathers the data) but not the chart. Also, for compatibility, the former Git versions chart is retained for now. The migration will be done in a future pull request.
The data format is as follows:
| date | Git version | users |
|---|---|---|
| 2018-03-27 | 2.16.1 | 2 |
| 2018-03-27 | 2.14.1 | 1 |
| 2018-03-27 | 2.12.2 | 1 |
| 2018-03-27 | 2.11.0 | 1 |
| 2018-03-27 | 2.10.2 | 1 |
| 2018-03-27 | 2.7.2 | 1 |
> Add detailed Git versions report

- updater/schema.py
By accident, newly created data repositories didn’t work with the updater. The reason is that the updater checked the data schema version but failed, because no `meta.tsv` file (which contains the data schema version) was present.
This adds a check that, if the `meta.tsv` file is not yet present, simply succeeds with the update, through which the data repository is populated with an up-to-date schema anyway.
In contrast to #146, this allows users to get started with an empty repository instead of having to create a `meta.tsv` manually and reading through some more documentation.
Closes #145.
> Support empty data repositories

- updater/reports/ReportPRUsage.py
I was now able to reproduce the issue of the missing `calendar` import that was mentioned in #136 and #146 by @IngoS11 and @primetheus.
I’m not entirely certain as to the reasons why the `calendar` module didn’t require an import before, but we’ll have to add the `import` statement anyway, because many users are probably affected.
So this adds the missing `import` directive.
Closes #136.
> Add missing Python import directive

- docs/demo-data/api-requests-by-user.tsv
- docs/housekeeping-api-requests.html
- updater/reports/ReportAPIRequestsByUser.py
- updater/scripts/api-requests-by-user.sh
- updater/update-stats.py
PR with a few minor improvements for #148
> Add API Requests By User

- updater/scripts/api-requests-by-user.sh
- updater/scripts/api-requests.sh
- updater/scripts/git-requests.sh
- updater/scripts/git-versions.sh
- updater/scripts/tokenless-auth.sh
Sometimes GHE entities (e.g. repo-, org-, team-, user-names) appear
with different casing in the log files. Ignore the casing when counting
these entities as they are generally case insensitive.
> ignore case when counting entities

- updater/reports/ReportGitDownload.py
- updater/scripts/git-lfs-download.sh
If there was no Git LFS traffic in the logs, then a user would see this
error:
```
File "hubble/updater/reports/ReportGitDownload.py", line 29, in updateDailyData
int(sumLFSTraffic[0][0]) // (1024 ** 3),
IndexError: list index out of range
```
Handle this case and report no Git LFS traffic properly.
---
While at it, I also made it work for *very* large Git LFS download number:
By default Perl uses scientific integer notation (e.g 2e+19) for very 
large integer numbers. The Python code would choke on it:
ValueError: invalid literal for int() with base 10: '2e+19'
Fix this by teaching Perl to always print the download number in
decimal form.
> git-download: handle the case if there is no Git LFS traffic

- docs/assets/js/_partials/chart-history.js
The history chart uses the `options.time.format` option to specify the date format of the *x* axis. [Chart.js deprecated this option](https://github.com/chartjs/Chart.js/blob/f815dd51968a0bec9305e1cf14d738d6f23c93aa/src/scales/scale.time.js#L454) in favor of the new option `options.time.parser`, which leads to warnings on the web console.
This pull request replaces the deprecated option with its successor.
> Replace deprecated Chart.js configuration option

- docs/spec/charts.js
By accident, these unit tests used the assignment operator `=` instead of the comparison operator `==`. This patch remedies the issue and, at the same time, switches to the more idiomatic `toEqual` method.
> Fix unit tests for time data aggregation

- updater/scripts/git-versions.sh
Previously we read the versions from the haproxy log and used the
originating IP address to distinguish machines/users. In a load balancer
setup this IP address can be the same for all requests and consequently
the number of users per version are not counted correctly.
Fix this by using the audit log to count the Git versions. Also count
the versions by user ID and not by IP address.
see https://github.com/Autodesk/hubble/issues/184
> read Git client versions from audit log

- updater/reports/ReportGitProtocol.py
If a protocol is not used, then we see no log lines about it. Therefore,
the existing code would throw a `KeyError` if we query the numbers from
the dictionary.
Fix this by using a default value.
> report 0 if a certain protocol is not used

- docs/_data/navigation.yml
- docs/demo-data/failed-webhooks-detailed.tsv
- docs/demo-data/failed-webhooks.tsv
- docs/housekeeping-failed-webhooks.html
- updater/reports/ReportFailedWebhooks.py
- updater/scripts/failed-webhooks.sh
- updater/update-stats.py
Add a view to display failed webhooks.
This can help to identify webhooks that are "clogging up" the `hookshots` queue and could safely be disabled, e.g. using `ghe-webhook-manage -d 1` on the management console.
```sh
$ ghe-webhook-manage 
Usage: ghe-webhook-manage [options] [hook_id]
Manage webhook status and locate where a hook is configured
OPTIONS:
-h              Show this message.
-s              Lookup a webhook's information (target, url, active status)
-e              Enable a webhook
-d              Disable a webhook
```
1. Open Hubble
2. Go to Housekeeping > Failed Webhooks: `/housekeeping-failed-webhooks`
> Add a view for failed webhooks

- docs/housekeeping-failed-webhooks.html
As discussed in https://github.com/Autodesk/hubble/pull/212#discussion_r501493171, adding information to the _Failed Webhooks_ page's info box.
1. Open Hubble
2. Go to Housekeeping > Failed Webhooks: `/housekeeping-failed-webhooks`
> Add information to failed webhooks info box

- docs/housekeeping-git-traffic.html
- docs/users-git-versions.html
`/var/log/github-audit.log` is used to query traffic and version info.
These log files are written on the node that serves the traffic and
Hubble only queries the log file on the primary. Therefore, in a configuration
with active replicas we are not reporting the right numbers.
Warn the user about it until we fix this.
> warn user about incorrect traffic and versions numbers with active replicas

- updater/scripts/git-download.sh
- updater/scripts/tokenless-auth.sh
These versions of GitHub Enterprise Server have been out of support for a long time, so let’s remove these version switches to keep things tidy.
> Drop unsupported GitHub Enterprise Server versions

- updater/reports/Report.py
In order to execute commands, `subprocess.Popen` expects a list of strings, where the first one represents the name of the command and the remaining strings are the command’s arguments. However, the `-s` option was included in the name of the binary, which isn’t supported in newer versions of Python anymore.
> Separate command arguments from name

- updater/reports/Report.py
- updater/reports/ReportAPIRequests.py
- updater/reports/ReportAPIRequestsByUser.py
- updater/reports/ReportContributorsByOrg.py
- updater/reports/ReportContributorsByRepo.py
- updater/reports/ReportFailedWebhooks.py
- updater/reports/ReportForksToOrgs.py
- updater/reports/ReportGitDownload.py
- updater/reports/ReportGitProtocol.py
- updater/reports/ReportGitRequests.py
- updater/reports/ReportGitVersions.py
- updater/reports/ReportGitVersionsNew.py
- updater/reports/ReportOrgActivity.py
- updater/reports/ReportOrgCollaboration.py
- updater/reports/ReportOrgOwners.py
- updater/reports/ReportOrgsAbandoned.py
- updater/reports/ReportOrgsTotal.py
- updater/reports/ReportPRByOrg.py
- updater/reports/ReportPRByRepo.py
- updater/reports/ReportPRHistory.py
- updater/reports/ReportPRUsage.py
- updater/reports/ReportRepoActivity.py
- updater/reports/ReportRepoSize.py
- updater/reports/ReportRepoUsage.py
- updater/reports/ReportReposPersonalNonOwnerPushes.py
- updater/reports/ReportRepositoryHistory.py
- updater/reports/ReportTeamsLegacy.py
- updater/reports/ReportTeamsTotal.py
- updater/reports/ReportTokenlessAuth.py
- updater/reports/ReportUsers.py
The function `executeScript` used to have a double role, as it was in charge of executing both Unix commands on the server (locally or by using a local connection) but also Bash scripts.
This was confusing per se, but had a few side effects that might have been unexpected to developers looking at the code.
First of all, the optional `stdin` argument was completely ignored when executing Bash scripts on the server. The reason for that is that `stdin` was used to pass the script’s content to the server (using the `-s` option provided by Bash). In a sense, the interface of this function was misleading as a result of this.
Also, when using `executeScript` to run regular Unix commands, unnecessary file look-ups were made.
To address these issues, this replaces the `executeScript` method with …
> Refactor functions for server calls

- updater/reports/Report.py
Ruby scripts were executed on the server by passing them to the GitHub environment runner as a command-line argument. This caused trouble with newlines, which were escaped with additional backslashes. However, it appears that this escaping may not be correct, depending on whether the command is run over SSH or not.
With this change, the Ruby script is not provided as a command-line argument anymore. Instead, the GitHub environment runner is instructed to read the Ruby script from `stdin`. This solution has the benefit of being more robust concerning newlines, as those don’t need to be escaped anymore. Also, this solution works regardless of other potentially confounding factors such as running the updater in a `systemd` environment vs. a remote shell or subprocess implementation …
> Fix Ruby script execution
